sudo: false
language: node_js
node_js:
- stable
script:
- npm test
notifications:
  slack:
    secure: wdcY8QZ936P4HXUQDkDfQ+gGuJ3MR0AnUu2WPvQbmpZIcoKefR1U5nBEvLcJcpg4Ix4RFZoAdtg+BlVNEnY3aoFtfV9nuUozVGpznr9MIPEtxjOyt4lb/Klk1g8L1Qi0afTg4rv2LR2hn9HjKiBYjxlOXuriOHgeuCwGo8otmeHXPvjOEbTroO5Jg/xNy02Smn7HSclLPj8rfMswijcL5yfTkfSeLjZmonSziv2CIhawvxa8iBsM9Y+9k/6B+iZF6sJVD7dSzSKH+dzv+9PyyUfLNB6Dmq0cBNmYZ7lpuCIijQme7CY6/NVpvE8DlEx8CGd1ysuhaCNr948dt/H4nP/oE5hCZLhH4acizcS58ugHtYvSYa+BDfdKMjatWbWzOjxEang7qmB9SXbfGPiLxLNl8icUuhdonMvFMHzoX7PZlJl5XuAf3wMp8BHAF3ObvwXY1juDMD38Ijb1Mw8tKG3GYpGLfuetc8gqd+QfKVoqI0Z+PqzRYlRYjq1OVbOQ3SDTAzFkbcIAc9kWMlVHLD1KdXXvXviq/LsDWYRvrpxjuFDIiBxrGkqAjT9qbgKT/6RtlWzCSLt0cbRswczyiBl4M+bZGRzLQ+YAiEWnF+znJQxyaLMprtLX4ZWjivfTp31uK1jdEVUpreEoOaN5DwbVvROYFKaKLfoRsLtjnRQ=
