sudo: false
language: node_js
node_js:
- stable
cache: yarn
deploy:
  provider: npm
  email: max@kupibilet.ru
  api_key:
    secure: kPIt0YVstGRXXvBFOLjN8Y3oB9KurzPuEWyFgPy5C41PH6s6TdBjuIx+oZz9tnqt1YuuIMqekTqaqKri+cavsKn+WlA9/xKEgtl5p2lwa1qM0W+0OU55EpCj7uvH8Y/33zgXiearm/pMlDCpBkCXu7AtII0tJFAhhu034PivVRsrp6ugw2La6L+8YILMSlTIO5jO9kjOL9wix3s4+VVhE8ZsAAdBJogpSAe1Kri/k+6+Z24sCYP0u8lVpKCjmf6taudfU/9a+MCpTTSky1LhRfiT0b3Hr9yvWq1NItr4N/Bjhd7rXziVwmIRnB2Ti+1f1kkpkXf8eWCUMNuVyCfyXikcWyHy7n33xtWsSq/2O3g8E16VSOx3D+qyip8Rd/xEYaDkPqCWQlnLERJMmNmtMIklN6VRGBkb+8uQxcHP+P0lbe7DSCHVuWq8Rot3uPF0bv20oCDBQRx/R6fFQJNMH3Re72R8pZl1ytoxV3TfzVUJqTKAjQx62dD/KrptQp04qqZNZ9eshUCN7f/vcxmRdWtPoBY3Cqa9SZGeLYpx/HfdyieF7Ety6ulwhlVPlq/oJIlM6lXUVs0Qe35ZRzMHrxezeGvZ9sD4OqFtQ9/MHmcpd1iG+3ArdWnLp5aZSvnSz6NeHA8D1r7ET+ZrsQOANQiTtkee8RlCEGiOHQEj7CA=
  on:
    branch: master
    tags: true
    repo: kupibilet-frontend/stylelint-config-kupibilet
