sudo: false
language: node_js
node_js:
- stable
cache: yarn
deploy:
  provider: npm
  email: max@kupibilet.ru
  api_key:
    secure: qkiba2/FcRHoPRs+m/grfBpqRi8oiMdpb4YggfCT+3pU+xAYouNGjk7pg/25lfwPHb9E0nUEo2CtPaniGD8+XRu+ZbbifpB8Q5lrnBk1yOVTqTjauErFtZs9qILkRy6YFrI8jp6fOfdemmxMBBMoCqeawn4Y9H5qxvjzF/zxCqFWDNM69ds5eND6SXCcox+/n9wMcApjKXHPHlXRep03w/l8BF45VJBDzz1k/5O4awIExHaVUN9ZmIUoAHE2u1aTI7HPrvP9floPeN4mnxQ3KA1cRvvChGHncgsfJVWKW1eshG6f4AoJuNCtCvKCtVHZjyMOnMULM7uYh/ZQxggfeR/D3oyWeZ243U2c5HAK/IWCi601EjBglA48evBTTcrBW83uR0/njpWPVQr7NzaQaVfOFJWlkMtNSDpjkxTMfHXIpdZFuef26RkXGspVOxDqiCYW/YXrNt+MUluM3wUPcZ5En+ndL8HyH0zUDDZc4JWr6QNce3t+WqEUngBsEKgpnhfvQ/j/t0pFC7Ut1XAUcXhc+7+ZFcueM6ISZQmCgE/5CUFXho4AsjmCN+wD1oSI9FMQHAp9bo+WOENifsEENni6CjwPr8RJthDRAkjI1PURIWlxjndW1E61ICU415HHNJLK2WhDMxMFufhLMwOpOjVxoqdpwv3/hyNB4zlMHL8=
  on:
    branch: master
    tags: true
    repo: kupibilet-frontend/stylelint-config-kupibilet
